name: "Parent Issue updater"
description: "Create epics from GitHub Issues using parent-child links"
author: "Taras Kushnir"
inputs:
  TOKEN:
    description: "Github token"
    default: ""
  REPO:
    description: "Github repository"
    default: ""
  DRY_RUN:
    description: "Do not update real issues"
    default: ""
  SYNC_DAYS:
    description: "Update issues changed in the last sync days"
    default: "1"
  ADD_CHANGELOG:
    description: "Add comments with updates made to parent issues"
    default: "1"
  MAX_LEVELS:
    description: "Show max levels of nested issues in parent"
    default: "0"
  UPDATE_CLOSED:
    description: "Update closed parent issues too"
    default: "0"

runs:
  using: "composite"
  steps:
    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version-file: ${{ github.action_path }}/go.mod

    - name: Run parent issue updater
      shell: bash
      working-directory: ${{ github.action_path }}
      env:
        INPUT_TOKEN: ${{ inputs.TOKEN }}
        INPUT_REPO: ${{ inputs.REPO }}
        INPUT_DRY_RUN: ${{ inputs.DRY_RUN }}
        INPUT_SYNC_DAYS: ${{ inputs.SYNC_DAYS }}
        INPUT_ADD_CHANGELOG: ${{ inputs.ADD_CHANGELOG }}
        INPUT_MAX_LEVELS: ${{ inputs.MAX_LEVELS }}
        INPUT_UPDATE_CLOSED: ${{ inputs.UPDATE_CLOSED }}
        GOFLAGS: -mod=vendor
        CGO_ENABLED: 0
      run: go run .

branding:
  icon: "link"
  color: "blue"
